### ISSUE TITLE
stdout 결과 출력 시 구분자 변경 및 출력과 엑셀 동시 사용하는 경우 추가

### ISSUE THREAD

**Issue by Leekyungun** [ppiazi/FilesInfoReader#16]
stdout으로 결과 출력시 현재 탭으로 구분을 하고 있다.
파싱할 때 파일이름에 스페이스가 들어갈 경우 파싱에 오류가 나타나는 현상이 발생하여
각 컬럼을 구분하는 구분자를 ' | '로 변경하고 싶음
현재는 ' | ' 이지만 파일명을 사용할 수 없는 ' / '도 괜찮을 것 같음

stdout으로 결과를 출력 할 경우 엑셀은 사용할 수 없다. 
-ostdout+ 을 입력할 시 stdout으로 결과 출력되고 default.xlsx 파일도 생성하도록 추가

**Comment by ppiazi** [comment]
파일이름에 들어갈 수 없는 문자 중 | 로 변경하도록 하겠음.
좋은 의견 쌩큐! ㅋㅋㅋ

**Comment by ppiazi** [comment]
3245367256cc90056e021612f6353c5f6a72cbd4

에서 수정완료. 단, -ostdout+ 입력시 별도의 default.xlsx로 생성하는 것은 별도의 이슈로 관리하겠음.
